### ISSUE TITLE
FIles which are uploaded to Temp directory are not getting deleted

### ISSUE THREAD

**Issue by yannalam** [wbstr/vaadin-multifileupload#11]
Hi
The files which are uploaded to the Temp Directory location are not getting deleted. It would be great if there is a Handler which returns the File object. 

Thanks

**Comment by andi0815** [comment]
Hi,

I was experiencing the same problem in our application. I found out that in our case the problem was our <code>UploadHandler</code> implementation did not close the InputStream given in:
<code>
   public void handleFile(InputStream, String, String, long)
</code>

You could consider some ways to mitigate that risk in the future:
<ol>
  <li>In the example/documentation: point out that the stream is expected to be closed by the handleFile()-implementation </li>
  <li>In <code>DefaultUploadReceiver.deleteTempFile()</code>: 
    <ul>
      <li>Remember the stream in a field and close the stream before trying to delete the file</li>
      <li>Log a warning, if file could not be deleted</li>
    </ul>
  </li>
</ol>

Thanks for the contribution!
Andi
Maybe you should point out

**Comment by juger89** [comment]
Fixed in 1.9.
